---
name: docker

on:
  push:
    branches: [main]

jobs:
  build:
    name: buildx
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: daluca/ycc:latest
