---
name: linting

on:
  pull_request:

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: prettier
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --check .
